
use vk;
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`) VALUES ('1', 'Reuben', 'Nienow', 'arlo50@example.org', '9374071116');
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`) VALUES ('2', 'Frederik', 'Upton', 'terrence.cartwright@example.org', '9127498182');
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`) VALUES ('3', 'Unique', 'Windler', 'rupert55@example.org', '9921090703');
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`) VALUES ('4', 'Norene', 'West', 'rebekah29@example.net', '9592139196');
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`) VALUES ('5', 'Frederick', 'Effertz', 'von.bridget@example.net', '9909791725');
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`) VALUES ('6', 'Victoria', 'Medhurst', 'sstehr@example.net', '9456642385');



INSERT INTO `cities` (`id`, `name`) VALUES ('1', 'London');
INSERT INTO `cities` (`id`, `name`) VALUES ('2', 'Baghdad');
INSERT INTO `cities` (`id`, `name`) VALUES ('3', 'Antalya');
INSERT INTO `cities` (`id`, `name`) VALUES ('4', 'Berlin');
INSERT INTO `cities` (`id`, `name`) VALUES ('5', 'Glasgow');
INSERT INTO `cities` (`id`, `name`) VALUES ('6', 'New York');
INSERT INTO `cities` (`id`, `name`) VALUES ('7', 'Prague');
INSERT INTO `cities` (`id`, `name`) VALUES ('8', 'Rome');
INSERT INTO `cities` (`id`, `name`) VALUES ('9', 'Riga');
INSERT INTO `cities` (`id`, `name`) VALUES ('10', 'Sydney');
INSERT INTO `cities` (`id`, `name`) VALUES ('11', 'Tokyo');
INSERT INTO `cities` (`id`, `name`) VALUES ('12', 'Helsinki');